task:
  type: HausdorffDistanceTask
  dataset: ModelNetPointset
  dataset_config:
    name: 10
    size: 256
  ood_dataset: ModelNetPointset
  ood_config:
    name: 10
    size: 512
backbone:
  type: CoupledNetwork
  latent_dimension: 32
  p: 1
  reconstruct_input: False
  decoder_distance: SinkhornLoss
  use_siamese: True
  aggregation: max
  encoder: 
    type: Transformer
    n_heads: 2
    n_layers: 2
    d_model: 128
    key_dim: 512
    feed_forward_hidden_dim: 128
  decoder:
    decoder_hidden_dim: 256
    decoder_n_layers: 3
batch_size: 128
learning_rate: 1.e-4
debug_mode: True
loss_function: mse_loss