task:
  type: WassersteinDistanceTask
  dataset: ModelNetPointset
  dataset_config:
    name: '10'
    size: 256
    length: 200
  ood_dataset: ModelNetPointset
  ood_config:
    name: '10'
    size: 512
    length: 200
backbone:
  type: CoupledNetwork
  latent_dimension: 32
  p: 1
  reconstruct_input: false
  decoder_distance: SinkhornLoss
  use_siamese: false
  aggregation: max
  encoder:
    type: Sumformer
    n_heads: 2
    n_layers: 2
    d_model: 128
    key_dim: 512
    feed_forward_hidden_dim: 128
  decoder:
    decoder_hidden_dim: 256
    decoder_n_layers: 3
batch_size: 128
learning_rate: 0.0001
debug_mode: true
loss_function: mse_loss
