task:
  type: ConvexHullMembershipTask
  dataset: SQUIDBoundaries
  dataset_config:
    normalization: True
  ood_dataset: SQUIDBoundaries
  ood_config:
    normalization: True
backbone:
  type: Sumformer
  n_heads: 1
  n_layers: 3
  d_model: 16
  feed_forward_hidden_dim: 64
batch_size: 32
learning_rate: 1.e-4
loss_function: scatter_binary_focal_loss