task:
  type: FrechetDistanceTask
  dataset: RandomTrajectory
  dataset_config:
    length: 100
    min_points: 10
    max_points: 20
    type: Langevin
    scaling: 10
  ood_dataset: RandomTrajectory
  ood_config:
    length: 10
    min_points: 15
    max_points: 25
    type: Langevin
    scaling: 10
backbone:
  type: CoupledNetwork
  latent_dimension: 32
  p: 1
  reconstruct_input: false
  decoder_distance: SinkhornLoss
  use_siamese: false
  aggregation: max
  encoder:
    type: SetNN
    d_model: 64
    embedding_layers: 2
    embedding_hidden_dim: 128
  positional_encoding: SinusoidalAbsolutePositionalEncoding
batch_size: 128
learning_rate: 0.0001
debug_mode: true
loss_function: mse_loss
