task:
  type: HausdorffDistanceTask
  dataset: GrowingCircles
  dataset_config:
    length: 3000
    min_points: 50
    max_points: 100
backbone:
  type: CoupledNetwork
  latent_dimension: 128
  p: 2
  reconstruct_input: False
  decoder_distance: SinkhornLoss
  encoder: 
    type: Sumformer
    n_heads: 1
    n_layers: 1
    d_model: 128
    key_dim: 512
    feed_forward_hidden_dim: 128
  decoder:
    type: Transformer
    n_heads: 12
    n_layers: 6
    d_model: 768
    key_dim: 512
    feed_forward_hidden_dim: 512
batch_size: 128
learning_rate: 1.e-4
debug_mode: True
