task:
  type: WassersteinDistanceTask
  dataset: ModelNet
  dataset_config:
    name: 10
backbone:
  type: CoupledNetwork
  latent_dimension: 128
  p: 1
  reconstruct_input: False
  use_siamese: True
  decoder_distance: SinkhornLoss
  encoder: 
    type: Sumformer
    n_heads: 1
    n_layers: 1
    d_model: 128
    key_dim: 512
    feed_forward_hidden_dim: 128
batch_size: 128
learning_rate: 1.e-4
debug_mode: True



