task:
  type: NearestNeighborRegressionTask
  dataset: GaussianBlobs
  dataset_config:
    length: 500
    min_points: 50
    max_points: 100
  ood_dataset: GaussianBlobs
  ood_config:
    length: 10
    min_points: 150
    max_points: 200
backbone:
  type: QueryNetwork
  encoder: 
    type: Sumformer
    n_heads: 2
    n_layers: 3
    d_model: 64
    feed_forward_hidden_dim: 128
batch_size: 64
learning_rate: 1.e-4
debug_mode: True
loss_function: mse_loss
