task:
  type: WassersteinDistanceTask
  dataset: GrowingCircles
  dataset_config:
    length: 100
backbone:
  type: CoupledNetwork
  latent_dimension: 256
  p: 2
  decoder_distance: SinkhornLoss
  encoder: 
    type: Transformer
    n_heads: 12
    n_layers: 6
    d_model: 768
    key_dim: 512
    feed_forward_hidden_dim: 512
  decoder:
    type: Transformer
    n_heads: 12
    n_layers: 6
    d_model: 768
    key_dim: 512
    feed_forward_hidden_dim: 512
batch_size: 12
learning_rate: 1.e-3
debug_mode: False
