name: test_sweep
metric:
  goal: minimize
  name: mean_error
method: grid
parameters:
  task:
    parameters:
      type: 
        values: [WassersteinDistanceTask]
      dataset: 
        values: [ModelNet]
      dataset_config:
        parameters:
          name: 
            values: ["10"]
  backbone:
    parameters:
      type: 
        values: [CoupledNetwork]
      latent_dimension: 
        values: [32, 64, 128, 256]
      p: 
        values: [1, 2]
      reconstruct_input:
        values: [False]
      decoder_distance: 
        values: [SinkhornLoss]
      encoder: 
        parameters:
          type: 
            values: [Transformer]
          n_heads: 
            values: [1, 2, 3, 4]
          n_layers: 
            values: [1, 2, 3]
          d_model: 
            values: [128, 256]
          key_dim: 
            values: [512]
          feed_forward_hidden_dim: 
            values: [128, 256, 512]
      decoder:
        parameters:
          type: 
            values: [Transformer]
          n_heads: 
            values: [12]
          n_layers: 
            values: [6]
          d_model: 
            values: [256]
          key_dim: 
            values: [512]
          feed_forward_hidden_dim: 
            values: [256]
  batch_size: 
    values: [64, 128]
  learning_rate: 
    value: 0.001
  n_epochs: 
    value: 1000

