task:
  type: ExtremalPointRegressionTask
  dataset: ModelNetPointset
  dataset_config:
    name: '10'
    length: 1000
    size: 256
  ood_dataset: ModelNetPointset
  ood_config:
    name: '10'
    length: 300
    size: 512
backbone:
  type: QueryNetwork
  encoder:
    type: SetNN
    d_model: 64
    embedding_layers: 2
    embedding_hidden_dim: 128
batch_size: 64
learning_rate: 1.e-4
debug_mode: True
loss_function: mse_loss

