task:
  type: ConvexHullMembershipTask
  dataset: SQUIDBoundaries
  dataset_config:
    normalization: True
  ood_dataset: SQUIDBoundaries
  ood_config:
    normalization: True
backbone:
  type: Sumformer
  n_heads: 1
  n_layers: 2
  d_model: 128
  key_dim: 512
  feed_forward_hidden_dim: 128
batch_size: 12
learning_rate: 1.e-4
loss_function: scatter_binary_cross_entropy