task:
  type: ConvexHullMembershipTask
  dataset: SQUIDBoundaries
  dataset_config:
    normalization: True
  ood_dataset: GaussianBlobs
  ood_config:
    length: 300
    min_points: 200
    max_points: 300
    centers: 4
    dim: 2
backbone:
  type: Transformer
  n_heads: 1
  n_layers: 2
  d_model: 128
  key_dim: 512
  feed_forward_hidden_dim: 128
batch_size: 128
learning_rate: 1.e-4
loss_function: scatter_binary_cross_entropy