task:
  type: RangeQueryTask
  dataset: RandomPolygons
  dataset_config:
    length: 3000
    min_points: 5
    max_points: 8
    scaling: 5
  ood_dataset: RandomPolygons
  ood_config:
    length: 100
    min_points: 5
    max_points: 12
    scaling: 5
backbone:
  type: QueryNetwork
  encoder: 
    type: Performer
    n_heads: 2
    n_layers: 3
    d_model: 64
    feed_forward_hidden_dim: 128
batch_size: 16
learning_rate: 1.e-4
debug_mode: True
loss_function: binary_cross_entropy_with_logits
aggregation: mean
