# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

"""SWIG wrapper for the CGAL Bounding volumes package provided under the GPL-3.0+ license"""

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _CGAL_Bounding_volumes
else:
    import _CGAL_Bounding_volumes

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import CGAL.CGAL_Kernel
class DoublePair(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _CGAL_Bounding_volumes.DoublePair_swiginit(self, _CGAL_Bounding_volumes.new_DoublePair(*args))
    first = property(_CGAL_Bounding_volumes.DoublePair_first_get, _CGAL_Bounding_volumes.DoublePair_first_set)
    second = property(_CGAL_Bounding_volumes.DoublePair_second_get, _CGAL_Bounding_volumes.DoublePair_second_set)
    def __len__(self):
        return 2
    def __repr__(self):
        return str((self.first, self.second))
    def __getitem__(self, index): 
        if not (index % 2):
            return self.first
        else:
            return self.second
    def __setitem__(self, index, val):
        if not (index % 2):
            self.first = val
        else:
            self.second = val
    __swig_destroy__ = _CGAL_Bounding_volumes.delete_DoublePair

# Register DoublePair in _CGAL_Bounding_volumes:
_CGAL_Bounding_volumes.DoublePair_swigregister(DoublePair)
class PairOfPairs(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _CGAL_Bounding_volumes.PairOfPairs_swiginit(self, _CGAL_Bounding_volumes.new_PairOfPairs(*args))
    first = property(_CGAL_Bounding_volumes.PairOfPairs_first_get, _CGAL_Bounding_volumes.PairOfPairs_first_set)
    second = property(_CGAL_Bounding_volumes.PairOfPairs_second_get, _CGAL_Bounding_volumes.PairOfPairs_second_set)
    def __len__(self):
        return 2
    def __repr__(self):
        return str((self.first, self.second))
    def __getitem__(self, index): 
        if not (index % 2):
            return self.first
        else:
            return self.second
    def __setitem__(self, index, val):
        if not (index % 2):
            self.first = val
        else:
            self.second = val
    __swig_destroy__ = _CGAL_Bounding_volumes.delete_PairOfPairs

# Register PairOfPairs in _CGAL_Bounding_volumes:
_CGAL_Bounding_volumes.PairOfPairs_swigregister(PairOfPairs)

def min_annulus_d(v, size):
    return _CGAL_Bounding_volumes.min_annulus_d(v, size)

def min_ellipse_2(input_vec, size):
    return _CGAL_Bounding_volumes.min_ellipse_2(input_vec, size)

